# prompt-wide option
# Disable the newline at the start of the prompt
add_newline = false

# format

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

[username]
disabled = false
style_root = "bold fg:red"
style_user = "bold fg:cyan"

[hostname]
disabled = false
style = "bold fg:green"
ssh_only = true
format = "[$hostname]($style) in"
# Linux
# 
# Windows
# 
# mac/apple
# 

[directory]
disabled = false
style = "bold fg:bright-green"
# fish_style_pwd_dir_length = 1
format = "[ $path]($style)[$lock_symbol]($lock_style) "

[git_branch]
disabled = false
style = "bold fg:bright-blue"
symbol = " "

[git_commit]
disabled = false
style = "bold bright-blue"

[git_state]
disabled = false
style = "bold bright-red"

[git_status]
disabled = false
style = "bold fg:red"
conflicted_count.enabled = false
modified_count.enabled = false
staged_count.enabled = false
show_sync_count = false

[dotnet]
disabled = true
# symbol = " "

[java]
disabled = true
# symbol = " "

[package]
disabled = false
# symbol = " "

[nodejs]
disabled = true
# symbol = " "

[golang]
disabled = true
# symbol = " "

[python]
disabled = true
pyenv_version_name = true
# symbol = " "

[ruby]
disabled = true
# symbol = " "

[cmd_duration]
disabled = false
style = "bold fg:green"

[env_var]
disabled = true



# [battery]
# full_symbol = ""
# charging_symbol = ""
# discharging_symbol = ""

