bar {
    status_command i3blocks
    position top
    font pango: Hack Nerd Font 10
    output eDP-1
    colors {
        background #1c1c1c
        statusline #e6e6e6
        separator #4f4f4f
        focused_workspace  #8be9fd #8be9fd #1c1c1c
        active_workspace   #282a36 #282a36 #f8f8f2
        inactive_workspace #3d3d3d #3d3d3d #808080
        urgent_workspace   #ff5555 #ff5555 #ffffff
    }
}
