general {
    lock_cmd = pidof hyprlock || hyprlock          # Evita iniciar hyprlock múltiples veces.
    before_sleep_cmd = loginctl lock-session      # Bloquea la sesión antes de suspender (Si decides suspender luego).
    after_sleep_cmd = hyprctl dispatch dpms on    # Evita pulsar tecla dos veces al despertar.
}

listener {
    timeout = 60                                  # 1 minuto
    on-timeout = brightnessctl -s set 5           # Reduce el brillo al mínimo (ideal para OLEDs).
    on-resume = brightnessctl -r                  # Restaura el brillo al detectar actividad.
}

listener {
    timeout = 120                                 # 2 minutos
    on-timeout = loginctl lock-session            # Bloquea la sesión de forma segura.
}



listener {
    timeout = 120                                 # 5 minutos
    on-timeout = hyprctl dispatch dpms off        # 🚨 APAGA LA PANTALLA (Power save mode).
    on-resume = hyprctl dispatch dpms on          # Enciende la pantalla al detectar actividad.
}

